### ISSUE TITLE
Release 2.1.6 to PyPI

### ISSUE THREAD

**Issue by kgadek** [vgrem/Office365-REST-Python-Client#167]
The release didn't happen [[1](https://travis-ci.org/kgadek/Office365-REST-Python-Client/requests)] due to some new errors. However, I don't see substantial changes since 2.1.5.

- fix Travis (code fixes? reconfigure account? retry later?)
- in case of any code changes, provide new tag `2.1.6-1`

Should be probably assigned on me, unless somebody knows what's going on.

**Comment by domdinicola** [comment]
@vgrem can you please follow up on pypi release?

**Comment by vgrem** [comment]
Hey guys!

I believe we are good to go now, unit tests have been fixed for Travis CI  in [`2.1.6-1` release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.1.6-1) 

@kgadek, @domdinicola,  thank you for your contributions!

**Comment by domdinicola** [comment]
Hey @vgrem,still not on pypi https://pypi.org/project/Office365-REST-Python-Client/#history

**Comment by kgadek** [comment]
The problem with Travis is still there unfortunately.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/185848/74202469-68634c00-4c64-11ea-8e4b-fa76c1453598.png">

**Comment by domdinicola** [comment]
should be fixed now https://travis-ci.org/vgrem/Office365-REST-Python-Client

**Comment by vgrem** [comment]
@kgadek  @domdinicola  not sure what  could be reason, in a master branch [no complains](https://travis-ci.org/vgrem/Office365-REST-Python-Client) from Travis CI

**Comment by domdinicola** [comment]
@vgrem any change we can trigger a manual package upload

**Comment by vgrem** [comment]
@domdinicola , not sure what exactly failed but my guess is one (of few) jobs (each job corresponds to specific Python version) have failed, as depicted on picture below:

![image](https://user-images.githubusercontent.com/1596072/74478030-3694f400-4eb5-11ea-85b1-706814ce07e1.png)

In that case i would suggest to restart the failed jobs(s). @kgadek, maybe you could assist in this regard?

**Comment by domdinicola** [comment]
@kgadek @vgrem can't you upload it manually with twine?

**Comment by domdinicola** [comment]
@vgrem @kgadek  if you grant me access to pypi I can help you creating the package with twine

**Comment by vgrem** [comment]
@domdinicola, since @kgadek is the maintainer, maybe he could assist this regard
