### ISSUE TITLE
"parent_folder" and "parent_collection" empty when retrieving file using "ctx.web.get_file_by_server_relative_url" (Sharepoint API)

### ISSUE THREAD

**Issue by BodoBurger** [vgrem/Office365-REST-Python-Client#764]
Python Version: 3.11
Office365-REST-Python-Client Version: 2.5.1

---

When I retrieve a file from Sharepoint using the method `ctx.web.get_file_by_server_relative_url(url).get().execute_query()` (or `ctx.web.get_file_by_server_relative_path`), it returns a `File` instance that has most of the properties, but `parent_folder` and `parent_collection` is `None`.
Because of this, the `copyto` method is not working as this method needs the parent collection.

**Is this the expected behaviour and is there a way to fetch the `parent_collection`?**

---

If I get a file via `ctx.web.get_folder_by_server_relative_url(url).get().execute_query()` the `File` instances have a `parent_collection` and the `copyto` method works on these `File` instances. However, copying a file to another folder this way requires a few more steps than if the `get_file_by_server_relative_url` method returned a file instance that had a `parent_collection`.

**Comment by vgrem** [comment]
Greetings,

thank you for filing this issue, indeed losing the context of the parent collection is the root cause, should be considered as a bug.

The aim to get it addressed in the next version.

**Comment by jsmatfess** [comment]
Python 3.10
Office365-REST-Python-Client Version: 2.5.1

FWIW this appears to be happening with the various `get_folder` functions as well. I've been attempting to copy folders and keep running into `NoneType object has no attribute add_child`. Inspecting the Folder object for the "from" folder, it appears that `parent_collection` is missing.

**Comment by vgrem** [comment]
Thank you again for catching and reporting it, it has been resolved [`2.5.2` release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.2)

**Comment by jsmatfess** [comment]
@vgrem I'm still getting this error with both folder.copy_to and folder.copy_to_using_path. `AttributeError: 'NoneType' object has no attribute 'add_child'`. I'm using 2.5.2.

```python
template = sp.web.get_folder_by_guest_url(folder_template_url).get().execute_query()
folder_path = f"Shared Documents/Copied Folder Test"
folder = template.copy_to_using_path(folder_path).execute_query()
```

The URL is definitely valid and `template.properties` returns everything you'd expect for a folder, so not sure what is happening here.

**Comment by JaanusPiip** [comment]
Python Version: 3.11
Office365-REST-Python-Client Version: 2.5.14

I seem to hit the same issue like this:
```
template = ctx.web.folders.get_by_path("DP Template library").get().execute_query()
folder_path = "My_folder/copy_tgt"
folder = template.copy_to_using_path(folder_path).execute_query()
```
